// Generated by CoffeeScript 1.7.1
(function() {
  var Bitfinex, assert;

  assert = require('assert');

  Bitfinex = require('../lib/Bitfinex');

  describe('fetch ticker', function() {
    return it('succeeds', function() {
      var bitfinex;
      bitfinex = new Bitfinex();
      return bitfinex.ticker('btcusd').then(function(result) {
        return assert(result.volume != null);
      });
    });
  });

  describe('fetch something private', function() {
    return it('errors when there is no key or secret', function() {
      var bitfinex, error;
      bitfinex = new Bitfinex();
      try {
        return bitfinex.balances();
      } catch (_error) {
        error = _error;
        return assert(error != null);
      }
    });
  });

}).call(this);
